package controller

const (
	BACKEND_PREFIX  = "BACKEND"
	FRONTEND_PREFIX = "FRONTEND"
	BIND_PREFIX     = "BIND"
	SERVER_PREFIX   = "POD."
	APP_NAME_PREFIX = "DEFAULT_APP."

	// V2 Service proxy constants
	SERVICE_BACKEND_PREFIX  = "SERVICE_BACKEND_"
	SERVICE_FRONTEND_PREFIX = "SERVICE_FRONTEND_"
	SERVICE_BIND_PREFIX     = "SERVICE_BIND_"
	SERVICE_SERVER_PREFIX   = "EP_"
)
